add

diff --git a/.github/workflows/validate_branch_names.yml b/.github/workflows/validate_branch_names.yml
--- a/.github/workflows/validate_branch_names.yml
+++ b/.github/workflows/validate_branch_names.yml
@@ -1,12 +1,19 @@
-name: Run on Branch Creation
+name: Validate branch names
 
 on:
   create
 
 jobs:
-  run-on-branch-create:
+  on-branch-create:
     if: startsWith(github.ref, 'refs/heads/')
     runs-on: ubuntu-latest
     steps:
-      - name: Announce branch creation
-        run: echo "Branch '${{ github.ref_name }}' was created by ${{ github.actor }}"
+      - name: Validate name
+        run: |
+            INVALID_CHARS='[<>:"/\\|?*]'
+            if [[ "${{ github.ref_name }}" =~ $INVALID_CHARS ]]; then
+                echo "Error: Branch name '${{ github.ref_name }}' created by ${{ github.actor }} contains invalid characters."
+                exit 1
+            else
+                echo "Branch name '${{ github.ref_name }}' is valid."
+            fi
